#!/bin/bash
max_epochs=60
samples=50
cores=20
#Num Epochs
echo Epoch male_err fem_err total_err MSETrain MSETest
#for i in $(seq 0 $max_epochs); do
i=0
while [ $i -lt $max_epochs ]; do
    for j in $(seq 1 $cores); do
	i=$[$i+1]
	(
	    a_tot=0 
	    b_tot=0
	    c_tot=0
	    d_tot=0
	    e_tot=0
	    #Num Samples per Epoch
	    k=0
	    for k in $(seq 1 $samples); do
		read a b c d e <<<$(nice ./train $i | cut -d ' ' -f 4,6,8,10,12 )
		a_tot=$(echo $a_tot + $a | bc )
		b_tot=$(echo $b_tot + $b | bc )
		c_tot=$(echo $c_tot + $c | bc )
		d_tot=$(echo $d_tot + $d | bc )
		e_tot=$(echo $e_tot + $e | bc )

	    done
	    #a_avg=$(echo $a_tot / $samples | bc )
	    a_avg=$(bc <<< "scale = 1; $a_tot / $samples")
	    b_avg=$(bc <<< "scale = 8; $b_tot / $samples")
	    c_avg=$(bc <<< "scale = 8; $c_tot / $samples")
	    d_avg=$(bc <<< "scale = 8; $d_tot / $samples")
	    e_avg=$(bc <<< "scale = 8; $e_tot / $samples")

	    echo -e $i'\t'$a_avg'\t'$b_avg'\t'$c_avg'\t'$d_avg'\t'$e_avg
	)&
	done
    wait
done

